// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    Head: typeof import('./src/components/Head/Head.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeSwiper: typeof import('./src/components/MainHome/HomeSwiper.vue')['default']
    LeftNav: typeof import('./src/components/LeftNav/LeftNav.vue')['default']
    LoginRegister: typeof import('./src/components/UserLogin/LoginRegister.vue')['default']
    MainHead: typeof import('./src/components/MainHead/MainHead.vue')['default']
    NewMusic: typeof import('./src/components/MainHome/NewMusic/NewMusic.vue')['default']
    RecommendPlaylist: typeof import('./src/components/RecommendPlaylist/RecommendPlaylist.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
